[package]
name = "tcp-listener-glommio"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.3.0"
env_logger = "0.10.0"
fastrand = "1.8.0"
futures = "0.3.5"
futures-lite = "1.11.1"
glommio = "0.7.0"
log = "0.4.17"
num_cpus = "1.13.0"
speedy = "0.8.5"
